name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version from CHANGELOG
        id: version
        run: |
          VERSION=$(grep -m 1 '## \[.*\]' CHANGELOG.md | sed -E 's/## \[(.*)\].*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ steps.version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        if: steps.check_tag.outputs.exists == 'false'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        if: steps.check_tag.outputs.exists == 'false'
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          LDFLAGS="-X main.version=${VERSION}"
          GOOS=darwin GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o cursor-fake-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "${LDFLAGS}" -o cursor-fake-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o cursor-fake-linux-amd64
          GOOS=windows GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o cursor-fake-windows-amd64.exe

      - name: Create Release
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.version.outputs.version }}
          CHANGELOG_CONTENT=$(awk "/## \[$VERSION\]/,/## \[.*\]/ { if (!/## \[.*\]/ || NR==1) print }" CHANGELOG.md | sed '1d')
          
          gh release create "$VERSION" \
            cursor-fake-darwin-amd64 \
            cursor-fake-darwin-arm64 \
            cursor-fake-linux-amd64 \
            cursor-fake-windows-amd64.exe \
            --title "Release $VERSION" \
            --notes "$CHANGELOG_CONTENT" \
            --target main 